export const defaultFormTemplates = [
  {
    name: 'Morning Milk Collection',
    description: 'Record cow-by-cow milk collection details for the current milking session.',
    category: 'milk',
    fields: [
      { fieldId: 'cowTagNumber', type: 'text', required: true, label: 'Cow tag / ear number', order: 1 },
      { fieldId: 'sessionDate', type: 'date', required: true, label: 'Collection date', order: 2 },
      { fieldId: 'sessionTime', type: 'time', required: true, label: 'Session time', order: 3 },
      { fieldId: 'session', type: 'select', required: true, label: 'Session', options: ['Morning', 'Afternoon', 'Evening'], order: 4 },
      { fieldId: 'yieldLitres', type: 'number', required: true, unit: 'litres', min: 0, max: 200, label: 'Milk yield', placeholder: 'e.g. 12.5', order: 5 },
      { fieldId: 'milkQuality', type: 'select', label: 'Milk appearance', options: ['Normal', 'Watery', 'Bloody', 'Abnormal colour'], order: 6 },
      { fieldId: 'conductivity', type: 'number', unit: 'mS/cm', label: 'Conductivity reading (if available)', order: 7 },
      { fieldId: 'mastitis', type: 'boolean', label: 'Mastitis signs observed?', order: 8 },
      { fieldId: 'notes', type: 'textarea', label: 'Any notes', order: 9 },
    ],
  },
  {
    name: 'Health Observation',
    description: 'Capture cow health observations before a manager reviews and transfers them.',
    category: 'health',
    fields: [
      { fieldId: 'cowTagNumber', type: 'text', required: true, label: 'Cow tag number', order: 1 },
      { fieldId: 'observationDate', type: 'date', required: true, label: 'Observation date', order: 2 },
      { fieldId: 'observationTime', type: 'time', required: true, label: 'Observation time', order: 3 },
      { fieldId: 'temperature', type: 'number', unit: 'C', min: 35, max: 42, label: 'Body temperature (if measured)', helpText: 'Normal range is usually around 38.0 to 39.5 C.', order: 4 },
      {
        fieldId: 'symptoms',
        type: 'multiselect',
        required: true,
        label: 'Symptoms',
        options: ['Lethargy', 'Loss of appetite', 'Limping', 'Diarrhoea', 'Nasal discharge', 'Eye discharge', 'Bloating', 'Difficulty breathing', 'Wound', 'Swollen udder', 'Other'],
        order: 5,
      },
      { fieldId: 'severity', type: 'select', required: true, label: 'Severity', options: ['Mild', 'Moderate', 'Severe'], order: 6 },
      { fieldId: 'vetCalled', type: 'boolean', label: 'Vet notified?', order: 7 },
      { fieldId: 'treatment', type: 'textarea', label: 'Treatment given (if any)', order: 8 },
      { fieldId: 'notes', type: 'textarea', label: 'Notes', order: 9 },
    ],
  },
  {
    name: 'Feed Distribution',
    description: 'Record feed issued to a cow, pen, paddock, or whole herd.',
    category: 'feed',
    fields: [
      { fieldId: 'distributionDate', type: 'date', required: true, label: 'Distribution date', order: 1 },
      { fieldId: 'distributionTime', type: 'time', required: true, label: 'Distribution time', order: 2 },
      { fieldId: 'cowTagNumber', type: 'text', label: 'Cow tag (leave blank for whole herd)', order: 3 },
      { fieldId: 'feedType', type: 'select', required: true, label: 'Feed type', options: ['Hay', 'Silage', 'Concentrate', 'Maize', 'Grass', 'Supplement', 'Other'], order: 4 },
      { fieldId: 'quantityKg', type: 'number', required: true, unit: 'kg', min: 0, label: 'Quantity', order: 5 },
      { fieldId: 'feedLocation', type: 'text', label: 'Pen or paddock', order: 6 },
      { fieldId: 'notes', type: 'textarea', label: 'Notes', order: 7 },
    ],
  },
  {
    name: 'Daily Expense',
    description: 'Capture farm expenses for manager review before posting to records.',
    category: 'expense',
    fields: [
      { fieldId: 'expenseDate', type: 'date', required: true, label: 'Expense date', order: 1 },
      { fieldId: 'category', type: 'select', required: true, label: 'Category', options: ['Feed purchase', 'Vet fees', 'Medicine', 'Labour', 'Equipment', 'Fuel', 'Utilities', 'Other'], order: 2 },
      { fieldId: 'description', type: 'text', required: true, label: 'What was purchased / paid for', order: 3 },
      { fieldId: 'amount', type: 'number', required: true, unit: 'KES', min: 0, label: 'Amount (KES)', order: 4 },
      { fieldId: 'paidTo', type: 'text', label: 'Paid to (supplier / person)', order: 5 },
      { fieldId: 'receiptNumber', type: 'text', label: 'Receipt or invoice number', order: 6 },
      { fieldId: 'paymentMethod', type: 'select', label: 'Payment method', options: ['Cash', 'M-Pesa', 'Bank transfer', 'Other'], order: 7 },
      { fieldId: 'notes', type: 'textarea', label: 'Notes', order: 8 },
    ],
  },
  {
    name: 'Calving Record',
    description: 'Capture paper or field details for calving events.',
    category: 'calving',
    fields: [
      { fieldId: 'motherTagNumber', type: 'text', required: true, label: 'Mother cow tag number', order: 1 },
      { fieldId: 'calvingDate', type: 'date', required: true, label: 'Calving date', order: 2 },
      { fieldId: 'calvingTime', type: 'time', label: 'Calving time', order: 3 },
      { fieldId: 'assistanceRequired', type: 'boolean', label: 'Assistance required during birth?', order: 4 },
      { fieldId: 'calfSex', type: 'select', required: true, label: 'Calf sex', options: ['Male', 'Female'], order: 5 },
      { fieldId: 'calfTagNumber', type: 'text', label: 'Calf tag number (if assigned)', order: 6 },
      { fieldId: 'birthWeightKg', type: 'number', unit: 'kg', min: 0, max: 80, label: 'Birth weight', order: 7 },
      { fieldId: 'calfCondition', type: 'select', required: true, label: 'Calf condition', options: ['Healthy', 'Weak', 'Stillborn', 'Requires vet attention'], order: 8 },
      { fieldId: 'placenta', type: 'boolean', label: 'Placenta passed?', order: 9 },
      { fieldId: 'notes', type: 'textarea', label: 'Notes', order: 10 },
    ],
  },
  {
    name: 'General Daily Report',
    description: 'Record field activities, herd checks, weather, and concerns.',
    category: 'general',
    fields: [
      { fieldId: 'reportDate', type: 'date', required: true, label: 'Report date', order: 1 },
      { fieldId: 'reportingWorker', type: 'text', label: 'Your name', order: 2 },
      { fieldId: 'activitiesCompleted', type: 'textarea', required: true, label: 'Activities completed today', order: 3 },
      { fieldId: 'animalsChecked', type: 'number', unit: 'cows', label: 'Number of animals checked', order: 4 },
      { fieldId: 'issuesObserved', type: 'textarea', label: 'Any issues or concerns', order: 5 },
      { fieldId: 'weatherConditions', type: 'select', label: 'Weather conditions', options: ['Sunny', 'Cloudy', 'Rainy', 'Very hot', 'Cold', 'Windy'], order: 6 },
      { fieldId: 'additionalNotes', type: 'textarea', label: 'Additional notes', order: 7 },
    ],
  },
];

export function buildDefaultFormTemplates({ farmId, createdBy }) {
  return defaultFormTemplates.map((template) => ({
    ...template,
    farmId,
    createdBy,
  }));
}
