import mongoose from 'mongoose';
const { Schema, model } = mongoose;
const opts = { timestamps: true };

const farmScoped = { farm: { type: Schema.Types.ObjectId, ref: 'Farm', index: true } };

export const Farm = model('Farm', new Schema({
  name: { type: String, required: true, default: 'My Dairy Farm' }, ownerName: String, phone: String, email: String, location: String,
  defaultMilkPrice: { type: Number, default: 50 }, currency: { type: String, default: 'KSh' }, reportFooter: { type: String, default: 'Generated by DairyTrack Pro' }
}, opts));

export const User = model('User', new Schema({
  name: { type: String, required: true }, email: { type: String, required: true, unique: true, lowercase: true }, passwordHash: { type: String, required: true },
  role: { type: String, enum: ['owner','manager','worker','viewer'], default: 'owner' }, farm: { type: Schema.Types.ObjectId, ref: 'Farm' }, active: { type: Boolean, default: true }
}, opts));

export const Cow = model('Cow', new Schema({ ...farmScoped,
  name: { type: String, required: true }, tagNumber: { type: String, index: true }, breed: String, dateOfBirth: Date, gender: { type: String, default: 'female' }, color: String,
  purchaseDate: Date, purchasePrice: Number, source: String, motherCow: String, fatherBull: String,
  status: { type: String, enum: ['milking','pregnant','dry','sick','calf','heifer','sold','dead'], default: 'milking' }, shedLocation: String, notes: String
}, opts));

export const MilkRecord = model('MilkRecord', new Schema({ ...farmScoped,
  cow: { type: Schema.Types.ObjectId, ref: 'Cow', required: true, index: true }, date: { type: Date, required: true, index: true },
  morningLitres: { type: Number, default: 0 }, afternoonLitres: { type: Number, default: 0 }, eveningLitres: { type: Number, default: 0 },
  milkSold: { type: Number, default: 0 }, milkUsedHome: { type: Number, default: 0 }, milkWasted: { type: Number, default: 0 }, pricePerLitre: { type: Number, default: 50 }, notes: String
}, opts));

export const HealthRecord = model('HealthRecord', new Schema({ ...farmScoped,
  cow: { type: Schema.Types.ObjectId, ref: 'Cow', required: true, index: true }, recordType: { type: String, enum: ['sickness','vaccination','deworming','injury','checkup'], default: 'sickness' },
  dateSick: Date, symptoms: String, diagnosis: String, medicineGiven: String, dosage: String, treatmentType: String, vetName: String, vetPhone: String,
  treatmentCost: { type: Number, default: 0 }, recoveryDate: Date, followUpDate: Date, notes: String
}, opts));

export const PregnancyRecord = model('PregnancyRecord', new Schema({ ...farmScoped,
  cow: { type: Schema.Types.ObjectId, ref: 'Cow', required: true, index: true }, heatDate: Date, inseminationDate: Date, breedingMethod: { type: String, enum: ['AI','bull'], default: 'AI' },
  bullOrSemenDetails: String, technicianName: String, pregnancyConfirmationDate: Date,
  pregnancyStatus: { type: String, enum: ['not_checked','confirmed_pregnant','not_pregnant','failed_insemination','delivered'], default: 'not_checked' },
  expectedDeliveryDate: Date, dryOffDate: Date, actualDeliveryDate: Date, calfBorn: Boolean, calfTagNumber: String, calfGender: String, calfStatus: String, complications: String, notes: String
}, opts));

export const FeedItem = model('FeedItem', new Schema({ ...farmScoped,
  name: { type: String, required: true }, category: String, currentStock: { type: Number, default: 0 }, unit: { type: String, default: 'kg' }, purchaseQuantity: Number, purchaseCost: Number,
  supplier: String, purchaseDate: Date, expiryDate: Date, dailyUsageEstimate: Number, lowStockThreshold: { type: Number, default: 10 }, notes: String
}, opts));

export const Expense = model('Expense', new Schema({ ...farmScoped,
  date: { type: Date, required: true }, category: String, amount: { type: Number, required: true }, cow: { type: Schema.Types.ObjectId, ref: 'Cow' }, description: String, paymentMethod: String
}, opts));

export const SaleRecord = model('SaleRecord', new Schema({ ...farmScoped,
  cow: { type: Schema.Types.ObjectId, ref: 'Cow', required: true }, buyerName: String, buyerPhone: String, buyerLocation: String, saleDate: Date, salePrice: Number, paymentStatus: String, amountPaid: Number, notes: String
}, opts));

export const Reminder = model('Reminder', new Schema({ ...farmScoped,
  title: String, type: String, cow: { type: Schema.Types.ObjectId, ref: 'Cow' }, dueDate: Date, priority: { type: String, default: 'medium' }, status: { type: String, default: 'pending' }, notes: String
}, opts));
