import mongoose from 'mongoose';

const { Schema, model } = mongoose;
const opts = { timestamps: true };

const farmScoped = { farm: { type: Schema.Types.ObjectId, ref: 'Farm', required: true, index: true } };
const ref = (modelName, extra = {}) => ({ type: Schema.Types.ObjectId, ref: modelName, ...extra });
const text = (extra = {}) => ({ type: String, trim: true, maxlength: 200, ...extra });
const amount = (extra = {}) => ({ type: Number, min: 0, ...extra });
const litres = (extra = {}) => ({ type: Number, min: 0, max: 200, ...extra });
const fieldCategories = ['milk', 'health', 'feed', 'expense', 'calving', 'vaccination', 'general'];
const fieldTypes = ['text', 'number', 'date', 'time', 'select', 'multiselect', 'boolean', 'photo', 'textarea'];

function applyStringDefaults(schema) {
  schema.eachPath((_, path) => {
    if (path.instance === 'String') {
      path.options.trim ??= true;
      path.options.maxlength ??= 200;
    }
  });
}

function excludeDeleted(next) {
  if (!this.getOptions().withDeleted) {
    this.where({ deletedAt: null });
  }
  next();
}

function createModel(name, definition, schemaOptions = opts) {
  const schema = new Schema(definition, schemaOptions);
  applyStringDefaults(schema);
  return mongoose.models[name] || model(name, schema);
}

const cowSchema = new Schema({
  ...farmScoped,
  name: text({ required: true }),
  tagNumber: text({ required: true, index: true }),
  breed: text(),
  dateOfBirth: Date,
  gender: text({ default: 'female' }),
  color: text(),
  purchaseDate: Date,
  purchasePrice: amount(),
  source: text(),
  motherCow: text(),
  fatherBull: text(),
  status: { type: String, enum: ['milking', 'pregnant', 'dry', 'sick', 'calf', 'heifer', 'sold', 'dead'], default: 'milking', trim: true, maxlength: 200 },
  shedLocation: text(),
  notes: text(),
  deletedAt: { type: Date, default: null, index: true },
}, opts);

applyStringDefaults(cowSchema);
cowSchema.pre('find', excludeDeleted);
cowSchema.pre('findOne', excludeDeleted);

export const Farm = createModel('Farm', {
  name: text({ required: true, default: 'My Dairy Farm' }),
  ownerName: text(),
  phone: text(),
  email: text(),
  location: text(),
  defaultMilkPrice: amount({ default: 50 }),
  currency: text({ default: 'KSh' }),
  reportFooter: text({ default: 'Generated by DairyTrack Pro' }),
});

export const User = createModel('User', {
  name: text({ required: true }),
  email: text({ required: true, unique: true, lowercase: true }),
  passwordHash: text({ required: true }),
  role: { type: String, enum: ['owner', 'manager', 'worker', 'viewer'], default: 'owner', trim: true, maxlength: 200 },
  farm: ref('Farm', { required: true }),
  active: { type: Boolean, default: true },
});

export const Cow = mongoose.models.Cow || model('Cow', cowSchema);

export const MilkRecord = createModel('MilkRecord', {
  ...farmScoped,
  cow: ref('Cow', { required: true, index: true }),
  date: { type: Date, required: true, index: true },
  morningLitres: litres({ default: 0 }),
  afternoonLitres: litres({ default: 0 }),
  eveningLitres: litres({ default: 0 }),
  milkSold: litres({ default: 0 }),
  milkUsedHome: litres({ default: 0 }),
  milkWasted: litres({ default: 0 }),
  pricePerLitre: amount({ default: 50 }),
  notes: text(),
  createdBy: ref('User'),
});

export const HealthRecord = createModel('HealthRecord', {
  ...farmScoped,
  cow: ref('Cow', { required: true, index: true }),
  recordType: { type: String, enum: ['sickness', 'vaccination', 'deworming', 'injury', 'checkup'], default: 'sickness', trim: true, maxlength: 200 },
  dateSick: Date,
  symptoms: text(),
  diagnosis: text(),
  medicineGiven: text(),
  dosage: text(),
  treatmentType: text(),
  vetName: text(),
  vetPhone: text(),
  treatmentCost: amount({ default: 0 }),
  recoveryDate: Date,
  followUpDate: Date,
  notes: text(),
});

export const PregnancyRecord = createModel('PregnancyRecord', {
  ...farmScoped,
  cow: ref('Cow', { required: true, index: true }),
  heatDate: Date,
  inseminationDate: Date,
  breedingMethod: { type: String, enum: ['AI', 'bull'], default: 'AI', trim: true, maxlength: 200 },
  bullOrSemenDetails: text(),
  technicianName: text(),
  pregnancyConfirmationDate: Date,
  pregnancyStatus: { type: String, enum: ['not_checked', 'confirmed_pregnant', 'not_pregnant', 'failed_insemination', 'delivered'], default: 'not_checked', trim: true, maxlength: 200 },
  expectedDeliveryDate: Date,
  dryOffDate: Date,
  actualDeliveryDate: Date,
  calfBorn: Boolean,
  calfTagNumber: text(),
  calfGender: text(),
  calfStatus: text(),
  complications: text(),
  notes: text(),
});

export const FeedItem = createModel('FeedItem', {
  ...farmScoped,
  name: text({ required: true }),
  category: text(),
  currentStock: amount({ default: 0 }),
  unit: text({ default: 'kg' }),
  purchaseQuantity: amount(),
  purchaseCost: amount(),
  supplier: text(),
  purchaseDate: Date,
  expiryDate: Date,
  dailyUsageEstimate: amount(),
  lowStockThreshold: amount({ default: 10 }),
  notes: text(),
});

export const Expense = createModel('Expense', {
  ...farmScoped,
  date: { type: Date, required: true },
  category: text({ required: true }),
  amount: amount({ required: true }),
  cow: ref('Cow'),
  description: text(),
  paymentMethod: text(),
});

export const SaleRecord = createModel('SaleRecord', {
  ...farmScoped,
  cow: ref('Cow', { required: true }),
  buyerName: text({ required: true }),
  buyerPhone: text(),
  buyerLocation: text(),
  saleDate: Date,
  salePrice: amount({ required: true }),
  paymentStatus: text(),
  amountPaid: amount(),
  notes: text(),
});

export const Reminder = createModel('Reminder', {
  ...farmScoped,
  title: text({ required: true }),
  type: text(),
  cow: ref('Cow'),
  dueDate: Date,
  priority: text({ default: 'medium' }),
  status: text({ default: 'pending' }),
  notes: text(),
});

export const Vaccination = createModel('Vaccination', {
  ...farmScoped,
  cowId: ref('Cow', { required: true, index: true }),
  vaccineType: text({ required: true }),
  dateGiven: { type: Date, required: true },
  nextDueDate: { type: Date, index: true },
  administeredBy: text(),
  batchNumber: text(),
  withdrawalPeriodDays: amount({ default: 0 }),
  notes: text(),
  createdBy: ref('User'),
  deletedAt: { type: Date, default: null, index: true },
});

export const MilkQuality = createModel('MilkQuality', {
  ...farmScoped,
  cowId: ref('Cow', { required: true, index: true }),
  testDate: { type: Date, required: true, index: true },
  scc: amount(),
  bacteriaCount: amount(),
  bodyConditionScore: { type: Number, min: 1, max: 5 },
  mastitis: { type: Boolean, default: false },
  testedBy: text(),
  notes: text(),
});

export const FeedInventory = createModel('FeedInventory', {
  ...farmScoped,
  feedType: text({ required: true }),
  stockKg: amount({ required: true }),
  costPerKg: amount({ required: true }),
  supplier: text(),
  lowStockThresholdKg: amount({ default: 50 }),
  lastRestocked: Date,
});

export const FeedConsumption = createModel('FeedConsumption', {
  ...farmScoped,
  feedId: ref('FeedInventory', { required: true, index: true }),
  cowId: ref('Cow', { default: null }),
  date: { type: Date, required: true, default: Date.now },
  quantityKg: amount({ required: true }),
  recordedBy: ref('User'),
});

export const Task = createModel('Task', {
  ...farmScoped,
  title: text({ required: true }),
  description: text(),
  assignedTo: ref('User', { required: true, index: true }),
  assignedBy: ref('User'),
  dueDate: { type: Date, required: true, index: true },
  status: { type: String, enum: ['pending', 'in-progress', 'complete', 'overdue'], default: 'pending', trim: true, maxlength: 200 },
  relatedCowId: ref('Cow'),
  priority: { type: String, enum: ['low', 'medium', 'high'], default: 'medium', trim: true, maxlength: 200 },
  completedAt: Date,
});

const formFieldSchema = new Schema(
  {
    fieldId: text({ required: true }),
    label: text({ required: true }),
    type: { type: String, enum: fieldTypes, required: true, trim: true, maxlength: 200 },
    required: { type: Boolean, default: false },
    options: [{ type: String, trim: true, maxlength: 200 }],
    unit: text(),
    min: Number,
    max: Number,
    placeholder: text(),
    helpText: text(),
    order: amount({ default: 0 }),
  },
  { _id: false },
);

const printHistorySchema = new Schema(
  {
    printedBy: ref('User'),
    printedAt: { type: Date, default: Date.now },
    copies: amount({ default: 1 }),
    notes: text(),
  },
  { _id: false },
);

export const FormTemplate = createModel('FormTemplate', {
  name: text({ required: true }),
  description: text(),
  category: { type: String, enum: fieldCategories, required: true, trim: true, maxlength: 200 },
  fields: [formFieldSchema],
  isActive: { type: Boolean, default: true },
  createdBy: ref('User'),
  farmId: ref('Farm', { required: true, index: true }),
  printHistory: [printHistorySchema],
});

export const FormSubmission = createModel('FormSubmission', {
  templateId: ref('FormTemplate', { required: true, index: true }),
  templateName: text({ required: true }),
  category: { type: String, enum: fieldCategories, required: true, trim: true, maxlength: 200 },
  submittedBy: ref('User', { required: true, index: true }),
  farmId: ref('Farm', { required: true, index: true }),
  farmData: { type: Schema.Types.Mixed, default: {} },
  status: {
    type: String,
    enum: ['draft', 'submitted', 'approved', 'rejected', 'transferred'],
    default: 'draft',
    trim: true,
    maxlength: 200,
    index: true,
  },
  workerNotes: text(),
  reviewedBy: ref('User'),
  reviewedAt: Date,
  reviewNotes: text(),
  transferredBy: ref('User'),
  transferredAt: Date,
  transferredRecordId: text(),
  transferredCollection: text(),
  isOfflineDraft: { type: Boolean, default: false },
  isManualEntry: { type: Boolean, default: false },
  deviceInfo: text(),
});

export const DailyReport = createModel('DailyReport', {
  farmId: ref('Farm', { required: true, index: true }),
  reportDate: { type: Date, required: true, index: true },
  reportingWorker: text(),
  activitiesCompleted: text({ required: true }),
  animalsChecked: amount(),
  issuesObserved: text(),
  weatherConditions: text(),
  additionalNotes: text(),
  submissionId: ref('FormSubmission'),
  submittedBy: ref('User'),
});

export const AuditLog = createModel('AuditLog', {
  farm: ref('Farm', { required: true, index: true }),
  actor: ref('User', { index: true }),
  action: text({ required: true, index: true }),
  entityType: text({ required: true, index: true }),
  entityId: text({ required: true, index: true }),
  summary: text({ required: true }),
  metadata: { type: Schema.Types.Mixed, default: {} },
});
