import dotenv from 'dotenv'; import mongoose from 'mongoose'; import bcrypt from 'bcryptjs';
import { Farm, User, Cow, MilkRecord, HealthRecord, PregnancyRecord, FeedItem, Expense, SaleRecord, Reminder } from './models.js';
dotenv.config();
if (!process.env.MONGO_URI) throw new Error('MONGO_URI is required before running the seed script.');
const d = (days) => new Date(Date.now() - days*86400000);
await mongoose.connect(process.env.MONGO_URI);
await Promise.all([Farm.deleteMany({}),User.deleteMany({}),Cow.deleteMany({}),MilkRecord.deleteMany({}),HealthRecord.deleteMany({}),PregnancyRecord.deleteMany({}),FeedItem.deleteMany({}),Expense.deleteMany({}),SaleRecord.deleteMany({}),Reminder.deleteMany({})]);
const farm = await Farm.create({ name:'Greenfield Dairy Farm', ownerName:'Ken Rodgers', phone:'+254700000000', location:'Nairobi, Kenya', defaultMilkPrice:50 });
const hash = await bcrypt.hash('password123',12);
await User.insertMany([{ name:'Owner', email:'owner@dairytrack.com', passwordHash:hash, role:'owner', farm:farm._id },{ name:'Manager', email:'manager@dairytrack.com', passwordHash:hash, role:'manager', farm:farm._id },{ name:'Worker', email:'worker@dairytrack.com', passwordHash:hash, role:'worker', farm:farm._id }]);
const names = [['Bella','DT-001','Friesian','milking'],['Nala','DT-002','Ayrshire','pregnant'],['Malaika','DT-003','Jersey Cross','milking'],['Zuri','DT-004','Guernsey','sick'],['Amani','DT-005','Fleckvieh','dry'],['Kito','DT-006','Friesian Cross','milking'],['Lulu','DT-007','Local Cross','heifer'],['Tamu','DT-008','Jersey','sold']];
const cows = await Cow.insertMany(names.map((n,i)=>({ farm:farm._id, name:n[0], tagNumber:n[1], breed:n[2], status:n[3], dateOfBirth:d(365*(3+i%5)), purchasePrice:60000+i*5000, color:i%2?'Brown':'Black & white' })));
let milks=[]; for (let day=0; day<35; day++) for (const c of cows.slice(0,6)) if(c.status!=='sold') milks.push({ farm:farm._id, cow:c._id, date:d(day), morningLitres:5+Math.random()*7, eveningLitres:4+Math.random()*6, milkSold:8+Math.random()*7, pricePerLitre:50 });
await MilkRecord.insertMany(milks);
await HealthRecord.insertMany([{farm:farm._id,cow:cows[3]._id,recordType:'sickness',dateSick:d(4),symptoms:'Low appetite',diagnosis:'Fever',medicineGiven:'Antibiotics',treatmentCost:2500},{farm:farm._id,cow:cows[0]._id,recordType:'vaccination',dateSick:d(60),diagnosis:'Routine vaccination',treatmentCost:700}]);
await PregnancyRecord.insertMany([{farm:farm._id,cow:cows[1]._id,inseminationDate:d(220),pregnancyStatus:'confirmed_pregnant',expectedDeliveryDate:new Date(Date.now()+63*86400000)},{farm:farm._id,cow:cows[4]._id,inseminationDate:d(290),pregnancyStatus:'delivered',actualDeliveryDate:d(7),calfBorn:true,calfGender:'female'}]);
await FeedItem.insertMany([{farm:farm._id,name:'Dairy Meal',category:'dairy_meal',currentStock:12,unit:'bags',lowStockThreshold:10,dailyUsageEstimate:1.5,purchaseCost:28000},{farm:farm._id,name:'Hay',category:'hay',currentStock:55,unit:'bales',lowStockThreshold:20,dailyUsageEstimate:3,purchaseCost:15000},{farm:farm._id,name:'Mineral Salts',category:'mineral_salts',currentStock:8,unit:'kg',lowStockThreshold:5,dailyUsageEstimate:.4,purchaseCost:3000}]);
await Expense.insertMany([{farm:farm._id,date:d(5),category:'feed',amount:28000,description:'Dairy meal restock'},{farm:farm._id,date:d(4),category:'vet',amount:2500,cow:cows[3]._id,description:'Vet treatment'},{farm:farm._id,date:d(1),category:'labour',amount:12000,description:'Worker wages'}]);
await SaleRecord.create({farm:farm._id,cow:cows[7]._id,buyerName:'Mr. Otieno',buyerPhone:'+254711111111',saleDate:d(10),salePrice:92000,paymentStatus:'paid',amountPaid:92000});
await Reminder.insertMany([{farm:farm._id,title:'Nala expected to calve soon',type:'calving',cow:cows[1]._id,dueDate:new Date(Date.now()+14*86400000),priority:'high'},{farm:farm._id,title:'Dairy meal low stock watch',type:'low_feed',dueDate:new Date(),priority:'medium'}]);
console.log('Seed complete'); await mongoose.disconnect();
